// Generated by https://quicktype.io

import { BookDTO } from '@/server/repositories/dto/BookDTO';
import { IProduct } from './product';
import { IClient } from './client';

export interface ICart {
  id: string;
  clientId: string;
  createdAt: string;
  updatedAt: string;
  productCart: IProductCart[];
  client?: IClient;
}
// Generated by https://quicktype.io

export interface IProductCart {
  id: string;
  cartId: string;
  bookId: string;
  amount: number;
  book: BookDTO;
  TradeRequest?: unknown;
  createdAt: string | Date;
  updatedAt: string | Date;
}
