// Generated by https://quicktype.io

import { IProduct } from './product';

export interface ICart {
  id: string;
  clientId: string;
  createdAt: string;
  updatedAt: string;
  productCart: IProductCart[];
}
// Generated by https://quicktype.io

export interface IProductCart {
  id: string;
  cartId: string;
  bookId: string;
  amount: number;
  book: IProduct;
  createdAt: string;
  updatedAt: string;
}
