import { BookStatus } from '@prisma/client';

export interface IProductDTO {
  name: string;
  isbn: string;
  author: string;
  year: number;
  publisher: string;
  edition: string;
  numberPages: number;
  categories: string[];
  synopsis: string;
  height: number;
  width: number;
  weight: number;
  depth: number;
  priceCost: number;
  manufacturer: string;
  priceGroupId:
    | '4c031611-75e5-479c-918f-8fa9e28a6e9f'
    | '691735f8-d892-4ebd-a371-bdc0a9ac4e1d'
    | '98361482-409a-470a-98d9-d9686f2a5d7e';
}
// Generated by https://quicktype.io

export interface IProduct {
  id: string;
  name: string;
  isbn: string;
  author: string;
  year: number;
  publisher: string;
  edition: string;
  numberPages: number;
  synopsis: string;
  height: number;
  width: number;
  weight: number;
  depth: number;
  priceCost: number;
  manufacturer: string;
  status: BookStatus;
  priceGroupId: string;
  createdAt: string;
  updatedAt: string;
  categories: ICategory[];
  priceSell: number;
  priceGroup?: IPriceGroup;
  stock: IStock;
  statusReason: IProductStatusReason[];
}
export interface IProductStatusReason {
  id: string;
  status: BookStatus;
  reason: string;
  createdAt: string;
  updatedAt: string;
}
export interface IPriceGroup {
  id: string;
  name: string;
  profitPercent: number;
  createdAt: string;
  updatedAt: string;
}
export interface ICategory {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}
// Generated by https://quicktype.io

export interface IStock {
  id: string;
  bookId: string;
  quantity: number;
  createdAt: string;
  updatedAt: string;
}
