import { BookStatus } from '@prisma/client';

export interface IProductDTO {
  name: string;
  isbn: string;
  author: string;
  year: number;
  publisher: string;
  edition: string;
  numberPages: number;
  categories: string[];
  synopsis: string;
  height: number;
  width: number;
  weight: number;
  depth: number;
  priceCost: number;
  manufacturer: string;
  priceGroupId:
    | '2c3f52d4-7ec3-4f53-8911-16fef2631f07'
    | '82f83b7e-c977-4c4d-856e-e389263c1923'
    | '984aa8e0-e0a1-40dc-9ec7-c420cde4be93';
}
// Generated by https://quicktype.io

export interface IProduct {
  id: string;
  name: string;
  isbn: string;
  author: string;
  year: number;
  publisher: string;
  edition: string;
  numberPages: number;
  synopsis: string;
  height: number;
  width: number;
  weight: number;
  depth: number;
  priceCost: number;
  manufacturer: string;
  status: BookStatus;
  priceGroupId: string;
  createdAt: string;
  updatedAt: string;
  categories: ICategory[];
  priceGroup: IPriceGroup;
  stock: IStock;
}

export interface IPriceGroup {
  id: string;
  name: string;
  profitPercent: number;
  createdAt: string;
  updatedAt: string;
}
export interface ICategory {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}
// Generated by https://quicktype.io

export interface IStock {
  id: string;
  bookId: string;
  quantity: number;
  createdAt: string;
  updatedAt: string;
}
